services:
  bdd-projet:
    image: ploc24/bdd-projet:1.0.0
    expose:
      - "3306"
    networks:
      - app

  api-projet:
    image: ploc24/api-projet:1.0.0
    depends_on:
      - bdd-projet
    ports:
      - "8082:8082"
    networks:
      - app

  front-projet:
    image: ploc24/front-projet:1.0.0
    depends_on:
      - api-projet
    ports:
      - "8080:8080"
    networks:
      - app

networks:
  app:
    driver: bridge
