services:
  bdd_projet:
    image: ploc24/bdd_projet
    expose:
      - "3306"
    networks:
      - backend

  api_projet:
    image: ploc24/api_projet
    depends_on:
      - bdd_projet
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"